export const hotels = [
    {
        id: 1,
        name: 'Marina Inn',
        description: 'Этот 4-звездочный отель расположен в центре города. На его территории есть бассейн с терассой и сауна. Из номеров открывается вид на море.',
        price: 4600,
        country: 'Албания',
        type: 'Отель',
        stars: 3,
        reviewsCount: 23,
    },
    {
        id: 2,
        name: 'Mondrian Suites',
        description: 'Этот 2-звездочный отель расположен в центре города.',
        price: 2600,
        country: 'Азербайджан',
        type: 'Апартаменты',
        stars: 2,
        reviewsCount: 4,
    },
    {
        id: 3,
        name: 'The Ritz',
        description: 'Этот 3-звездочный отель расположен в центре города.',
        price: 3500,
        country: 'Австралия',
        type: 'Отель',
        stars: 4,
        reviewsCount: 5,
    },
    {
        id: 4,
        name: 'Marina Inn',
        description: 'Этот 4-звездочный отель расположен в центре города. На его территории есть бассейн с терассой и сауна. Из номеров открывается вид на море.',
        price: 4600,
        country: 'Албания',
        type: 'Отель',
        stars: 3,
        reviewsCount: 23,
    },
    {
        id: 5,
        name: 'Mondrian Suites',
        description: 'Этот 2-звездочный отель расположен в центре города.',
        price: 2600,
        country: 'Азербайджан',
        type: 'Апартаменты',
        stars: 2,
        reviewsCount: 4,
    },
    {
        id: 6,
        name: 'The Ritz',
        description: 'Этот 3-звездочный отель расположен в центре города.',
        price: 3500,
        country: 'Австралия',
        type: 'Отель',
        stars: 4,
        reviewsCount: 5,
    },
    {
        id: 7,
        name: 'Marina Inn',
        description: 'Этот 4-звездочный отель расположен в центре города. На его территории есть бассейн с терассой и сауна. Из номеров открывается вид на море.',
        price: 4600,
        country: 'Албания',
        type: 'Отель',
        stars: 3,
        reviewsCount: 23,
    },
    {
        id: 8,
        name: 'Mondrian Suites',
        description: 'Этот 2-звездочный отель расположен в центре города.',
        price: 2600,
        country: 'Азербайджан',
        type: 'Апартаменты',
        stars: 2,
        reviewsCount: 4,
    },
    {
        id: 9,
        name: 'The Ritz',
        description: 'Этот 3-звездочный отель расположен в центре города.',
        price: 3500,
        country: 'Австралия',
        type: 'Отель',
        stars: 4,
        reviewsCount: 5,
    },
    {
        id: 10,
        name: 'Marina Inn',
        description: 'Этот 4-звездочный отель расположен в центре города. На его территории есть бассейн с терассой и сауна. Из номеров открывается вид на море.',
        price: 4600,
        country: 'Албания',
        type: 'Отель',
        stars: 3,
        reviewsCount: 23,
    },
    {
        id: 11,
        name: 'Mondrian Suites',
        description: 'Этот 2-звездочный отель расположен в центре города.',
        price: 2600,
        country: 'Азербайджан',
        type: 'Апартаменты',
        stars: 2,
        reviewsCount: 4,
    },
    {
        id: 12,
        name: 'The Ritz',
        description: 'Этот 3-звездочный отель расположен в центре города.',
        price: 3500,
        country: 'Австралия',
        type: 'Отель',
        stars: 4,
        reviewsCount: 5,
    },
    {
        id: 13,
        name: 'Marina Inn',
        description: 'Этот 4-звездочный отель расположен в центре города. На его территории есть бассейн с терассой и сауна. Из номеров открывается вид на море.',
        price: 4600,
        country: 'Албания',
        type: 'Отель',
        stars: 3,
        reviewsCount: 23,
    },
    {
        id: 14,
        name: 'Mondrian Suites',
        description: 'Этот 2-звездочный отель расположен в центре города.',
        price: 2600,
        country: 'Азербайджан',
        type: 'Апартаменты',
        stars: 2,
        reviewsCount: 4,
    },
    {
        id: 15,
        name: 'The Ritz',
        description: 'Этот 3-звездочный отель расположен в центре города.',
        price: 3500,
        country: 'Австралия',
        type: 'Отель',
        stars: 4,
        reviewsCount: 5,
    },
    {
        id: 16,
        name: 'Marina Inn',
        description: 'Этот 4-звездочный отель расположен в центре города. На его территории есть бассейн с терассой и сауна. Из номеров открывается вид на море.',
        price: 4600,
        country: 'Албания',
        type: 'Отель',
        stars: 3,
        reviewsCount: 23,
    },
    {
        id: 17,
        name: 'Mondrian Suites',
        description: 'Этот 2-звездочный отель расположен в центре города.',
        price: 2600,
        country: 'Азербайджан',
        type: 'Апартаменты',
        stars: 2,
        reviewsCount: 4,
    },
    {
        id: 18,
        name: 'The Ritz',
        description: 'Этот 3-звездочный отель расположен в центре города.',
        price: 3500,
        country: 'Австралия',
        type: 'Отель',
        stars: 4,
        reviewsCount: 5,
    },
    {
        id: 19,
        name: 'Marina Inn',
        description: 'Этот 4-звездочный отель расположен в центре города. На его территории есть бассейн с терассой и сауна. Из номеров открывается вид на море.',
        price: 4600,
        country: 'Албания',
        type: 'Отель',
        stars: 3,
        reviewsCount: 23,
    },
    {
        id: 20,
        name: 'Mondrian Suites',
        description: 'Этот 2-звездочный отель расположен в центре города.',
        price: 2600,
        country: 'Азербайджан',
        type: 'Апартаменты',
        stars: 2,
        reviewsCount: 4,
    },
    {
        id: 21,
        name: 'The Ritz',
        description: 'Этот 3-звездочный отель расположен в центре города.',
        price: 3500,
        country: 'Австралия',
        type: 'Отель',
        stars: 4,
        reviewsCount: 5,
    },
];

export const countries = [
    'Австрия',
    'Австралия',
    'Азербайджан',
    'Албания',
    'Алжир',
    'Ангола',
    'Ангилья',
    'Андорра',
    'Антарктида',
    'Аргентина',
];

export const types = [
    'Апартаменты',
    'Отель',
];

export const stars = [
    '1 звезда',
    '2 звезды',
    '3 звезды',
    '4 звезды',
    '5 звезд',
];